spring.application.name=IronManager


spring.datasource.url=jdbc:mysql://localhost:3306/application
spring.datasource.username=root
spring.datasource.password=om@12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update